---
format: gfm
metadata-files:
  - _metadata.yml
---

# {{< meta gh.repo >}}: TODO add more to title

{{< include /includes/_badges.qmd >}}

<!-- TODO: Add description of project -->

::: callout-tip
This website repository was generated from the
[`template-website`](https://github.com/seedcase-project/template-website)
Seedcase template :tada:
:::

## Project files and folders

- `.copier-answers.yml`: Contains the answers you gave when copying the
  project from the template.
  **You should not modify this file directly.**
- `.cz.toml`:
  [Commitizen](https://commitizen-tools.github.io/commitizen/)
  configuration file for managing versions and changelogs.
- `.pre-commit-config.yaml`: [Pre-commit](https://pre-commit.com/)
  configuration file for managing and running checks before each commit.
- `.typos.toml`: [typos](https://github.com/crate-ci/typos) spell
  checker configuration file.
- `.zenodo.json`: Structured citation metadata for your project when
  archived on [Zenodo](https://zenodo.org/). This is used to add the
  metadata to Zenodo when a GitHub release has been uploaded to Zenodo.
- `justfile`: [`just`](https://just.systems/man/en/) configuration file
  for scripting project tasks.
- `.editorconfig`: Editor configuration file for
  [EditorConfig](https://editorconfig.org/) to maintain consistent
  coding styles across different editors and IDEs.
- `CHANGELOG.md`: Changelog file for tracking changes in the project.
- `CONTRIBUTING.md`: Guidelines for contributing to the project.
- `.github/`: Contains GitHub-specific files, such as issue and pull
  request templates, workflows,
  [dependabot](https://docs.github.com/en/code-security/getting-started/dependabot-quickstart-guide)
  configuration, pull request templates, and a
  [CODEOWNERS](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/about-code-owners)
  file.
- `_metadata.yml`: Quarto metadata file for the website, including
  information about the project, such as the titles and GitHub names.
- `_quarto.yml`: Quarto configuration file for the website, including
  settings for the website, such as the theme, navigation, and other
  options.
- `.rumdl.toml`: [rumdl](https://rumdl.dev) configuration file for
  formatting Markdown files in the project.

## Contributing

Check out our [contributing document](CONTRIBUTING.md) for information
on how to contribute to the project, including how to set up your
development environment.

Please note that this project is released with a
[Contributor Code of Conduct](CODE_OF_CONDUCT.md). By participating in
this project you agree to abide by its terms.

::: content-hidden
<!-- TODO: Unhide when there are more contributors -->
### Contributors

{{< include /includes/_contributors.qmd >}}
:::

## Licensing

This project is licensed under the [CC-BY-4.0 License](LICENSE.md).

## Changelog

For a list of changes, see our [changelog](CHANGELOG.md) page.
