---
title: "Installing"
description: |
  Instructions for installing the required (and optional) programs to use this
  template and create a new Quarto-based website project from it.
order: 1
---

There are a few programs that are required to use this template to create a
website project:

- [uv](https://docs.astral.sh/uv/): A tool for managing Python environments and
  running commands.
- [Python](https://www.python.org/): Required by Copier, the template tool.
- [Copier](https://copier.readthedocs.io/en/stable/): A template tool for making
  new projects in a standardised and structured way.

You can use uv to install these required programs, so
[install](https://docs.astral.sh/uv/getting-started/installation/) that first.
After you've installed uv, you can use uv to install Copier, which is the
program that will actually take the template and set it up on your computer.

```bash {filename="Terminal"}
uv tool install copier
```

uv will also install Python for you when you install Copier. After that, in
order to do the [next steps](next-steps.qmd) and to use the website project
created from the template, you need to install:

- [Git](https://git-scm.com/): For version control and setting up Git to track
  the newly created website.
- [Quarto](https://quarto.org/): A scientific and technical publishing system
  built on Pandoc. The website built with this template is created with Quarto,
  and the PROJECT created from this template is also set up to use Quarto too.
- [gh cli](https://cli.github.com/): For managing GitHub repositories and
  settings from the command line. There are some post-creation steps we've
  included that use gh to simplify setting up a GitHub repository for the
  website project.

We **strongly recommend** installing and using these tools to help make it
easier to develop the website material created with this template:

- [Lychee](https://lychee.cli.rs/guides/getting-started/): A link checker that
  we include in the `justfile` for checking for broken links in the files.

- [just](https://just.systems/man/en/): A build and development management tool
  that helps with running common build and check tasks. You can install it using
  uv.

  ```bash {filename="Terminal"}
  uv tool install rust-just
  ```

If you write any Python or R code in your website project, we recommend you
install these other programs as well to format and check your code inside your
Quarto files.

To format and check R code, install [Jarl](https://jarl.etiennebacher.com) and
[Air](https://github.com/posit-dev/air):

```bash {filename="Terminal"}
uv tool install jarl-linter
uv tool install air-formatter
```

To format and check Python code, install [Ruff](https://docs.astral.sh/ruff/):

```bash {filename="Terminal"}
uv tool install ruff
```
