[files]
extend-exclude = [
  "*.html",
  "*.css",
  ".quarto/*",
  "_site/*",
  "*.svg",
  # If creating releases and using git-cliff, the hashes in the CHANGELOG can
  # falsely trigger typos.
  "CHANGELOG.md",
]
