name: Test template

on:
  push:
    branches:
      - main
  pull_request:

# Least privilege permissions
permissions: read-all

jobs:
  test-copier:
    uses: seedcase-project/.github/.github/workflows/reusable-test-copier.yml@main
    with:
      test-recipe: "_tests"
